### ISSUE TITLE
OSC manager crashes if launched when default port is bound by another program

### ISSUE THREAD

**Issue by Ari-VRC** [DASPRiD/vrc-osc-manager#1] opened 2023-05-22 01:59 UTC
I had another program running and occupying port 9001, and when attempting to launch the OSC manager it immediately crashes but the process is still running. I am unable to kill the zombie process through task manager as it does not show up in the list of running applications, but i can not relaunch the manager afterwards. needing powertoys to search for what is using the exe to kill it.

**Comment by DASPRiD** [comment] 2023-05-22 09:38
I just tried re-creating the issue in a Windows 10 VM, but was unable reproduce it. Looking at the log file, it does exit cleanly and when unblocking the port, I can just restart OSC manager.

Which Windows version are you running this on exactly, and could you post the log file contents? They should be somewhere in your `AppData` directory in your home directory, unter `Roaming/vrc-osc-manger`.

**Comment by DASPRiD** [comment] 2023-05-22 09:50
Also, does powertoys show you information about what is left behind?

**Comment by DASPRiD** [comment] 2023-05-22 12:10
I just retried in a Windows 11 VM, but could still not reproduce it. Which is the other program you are using, which was blocking the port?

**Comment by DASPRiD** [comment] 2023-09-23 12:21
Since there was no more update on this issue, and with OSC Query support it will always use a fresh port, I gonna close this issue for now.

**Closed as completed by DASPRiD** 2023-09-23 12:21 UTC
Labels: bug
